export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const POST_BOOK_REQUEST = 'POST_BOOK_REQUEST';
export const POST_BOOK_SUCCESS = 'POST_BOOK_SUCCESS';
export const POST_BOOK_FAILURE = 'POST_BOOK_FAILURE';

export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
export const CLEAN_BOOKS = 'CLEAN_BOOKS';

export const FETCH_GBOOKS_SUCCESS = 'FETCH_GBOOKS_SUCCESS';
export const FETCH_GBOOKS_REQUEST = 'FETCH_GBOOKS_REQUEST';
export const FETCH_GBOOKS_FAILURE = 'FETCH_GBOOKS_FAILURE';
export const CLEAN_GBOOK = 'CLEAN_GBOOK';




